FROM php:8.3-fpm-alpine

RUN apk update && \
    apk upgrade && \
    apk add curl nano zip wget bash

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd pdo_pgsql xdebug apcu intl zip bcmath curl opcache xml

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
